package com.knowyourinterview.api.experience;

import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import com.knowyourinterview.api.common.PagedResponse;
import com.knowyourinterview.api.experience.dto.ExperienceTeaserResponse;
import com.knowyourinterview.api.support.ContainerConfig;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The real safety net for the Tier 1 (normalized "contains" filters) + Tier 2 (typo-tolerant,
 * relevance-ranked search) browse rewrite. {@code ExperienceRepository#browsePublished} is a
 * hand-written NATIVE query using pg_trgm {@code similarity()}, the V15 generated columns
 * ({@code company_normalized} etc.), and a computed ORDER BY — none of which a mocked
 * repository or the JPQL-parsing test harness can catch. Everything here runs against a real
 * Flyway-migrated Postgres via Testcontainers. Run with {@code mvn verify} (needs Docker).
 *
 * <p>Seeds rows straight through {@link JdbcTemplate} (the generated columns are computed by
 * Postgres, so they're never inserted) and drives the real {@link ExperienceService}, so the
 * service's normalize()/param-building and the SQL are exercised end to end.
 */
@SpringBootTest
@Import(ContainerConfig.class)
class BrowseSearchIT {

    /**
     * A touch below pg_trgm's 0.3 default so the deliberately-noisy typo case ("bakend" vs
     * "Backend Engineer") clears the bar — the whole point of Tier 2 is to catch typos the
     * substring match misses. The other cases don't depend on the exact cutoff.
     */
    @DynamicPropertySource
    static void searchProperties(DynamicPropertyRegistry registry) {
        registry.add("app.search.similarity-threshold", () -> "0.2");
        // No test may open an SMTP connection; blank host => LoggingEmailSender.
        registry.add("spring.mail.host", () -> "");
    }

    @Autowired
    private ExperienceService experienceService;

    @Autowired
    private JdbcTemplate jdbc;

    private UUID contributorId;

    @BeforeEach
    void seedContributor() {
        // Shared context across methods — start each test from an empty catalogue.
        jdbc.execute("TRUNCATE experiences, users CASCADE");
        contributorId = UUID.randomUUID();
        jdbc.update(
                "INSERT INTO users (id, email, password_hash, display_name, is_admin, email_verified) "
                        + "VALUES (?, ?, 'x', 'Seed Contributor', false, true)",
                contributorId, "seed-" + contributorId + "@example.test");
    }

    /** Inserts a PUBLISHED experience and returns its id. Normalized columns are generated by
     * Postgres, so they're deliberately not in the column list. */
    private UUID seedPublished(String company, String roleTitle, String level, String teaser,
                               long pricePaise, Instant publishedAt) {
        UUID id = UUID.randomUUID();
        jdbc.update("""
                INSERT INTO experiences
                    (id, contributor_id, company, role_title, level, is_remote, outcome, teaser,
                     price_paise, status, is_free, created_at, updated_at, published_at)
                VALUES (?, ?, ?, ?, ?, false, 'OFFER', ?, ?, 'PUBLISHED', false, now(), now(), ?)
                """,
                id, contributorId, company, roleTitle, level, teaser, pricePaise,
                Timestamp.from(publishedAt));
        return id;
    }

    private PagedResponse<ExperienceTeaserResponse> browse(String company, String roleTitle, String level,
                                                           Short year, Boolean isFree, String search, String sort) {
        return experienceService.browsePublished(
                null, company, roleTitle, level, year, isFree, search, sort, 0, 50);
    }

    @Test
    void roleFilterMatchesAcrossPunctuationDifferences() {
        Instant now = Instant.now();
        seedPublished("Acme", "SDE-3", "L5", "Interview experience.", 9900, now);

        // Tier 1: "SDE3" normalizes to "sde3" and matches the stored "SDE-3" (also "sde3").
        PagedResponse<ExperienceTeaserResponse> page = browse(null, "SDE3", null, null, null, null, "newest");

        assertThat(page.items())
                .extracting(ExperienceTeaserResponse::roleTitle)
                .containsExactly("SDE-3");
    }

    @Test
    void partialRoleFilterReturnsEveryMatchingLevel() {
        Instant now = Instant.now();
        seedPublished("Acme", "SDE-1", "L3", "One.", 9900, now);
        seedPublished("Globex", "SDE-2", "L4", "Two.", 9900, now);
        seedPublished("Initech", "SDE-3", "L5", "Three.", 9900, now);
        seedPublished("Umbrella", "Designer", "L4", "Not an SDE.", 9900, now);

        // Typing just "sde" returns every SDE-* role and nothing else.
        PagedResponse<ExperienceTeaserResponse> page = browse(null, "sde", null, null, null, null, "newest");

        assertThat(page.items())
                .extracting(ExperienceTeaserResponse::roleTitle)
                .containsExactlyInAnyOrder("SDE-1", "SDE-2", "SDE-3");
    }

    @Test
    void keywordSearchToleratesTyposViaTrigramSimilarity() {
        Instant now = Instant.now();
        seedPublished("Acme", "Backend Engineer", "L5", "Interview experience.", 9900, now);
        seedPublished("Globex", "Frontend Designer", "L4", "Interview experience.", 9900, now);

        // "bakend" is a typo — it matches neither the normalized-contains nor the teaser
        // substring, so this only passes if the pg_trgm similarity path fires.
        PagedResponse<ExperienceTeaserResponse> page = browse(null, null, null, null, null, "bakend", "newest");

        assertThat(page.items())
                .extracting(ExperienceTeaserResponse::roleTitle)
                .containsExactly("Backend Engineer");
    }

    @Test
    void searchResultsAreRankedByRelevanceClosestFirst() {
        Instant earlier = Instant.now().minus(2, ChronoUnit.HOURS);
        Instant later = Instant.now();
        // Exact company match, published EARLIER.
        seedPublished("Stripe", "Engineer", "L5", "Interview experience.", 9900, earlier);
        // Weaker (substring) match, published LATER — newest-first would put this first, so
        // this row appearing SECOND proves relevance wins over recency.
        UUID weaker = seedPublished("Stripe Payments Platform", "Engineer", "L5",
                "Interview experience.", 9900, later);

        PagedResponse<ExperienceTeaserResponse> page = browse(null, null, null, null, null, "stripe", "newest");

        assertThat(page.items()).hasSize(2);
        assertThat(page.items().get(0).company()).isEqualTo("Stripe");
        assertThat(page.items().get(1).id()).isEqualTo(weaker);
    }

    @Test
    void nonSearchPriceLowSortOrdersByPriceAscending() {
        Instant now = Instant.now();
        seedPublished("Acme", "Engineer", "L5", "Pricey.", 30000, now);
        seedPublished("Globex", "Engineer", "L4", "Cheap.", 10000, now);
        seedPublished("Initech", "Engineer", "L3", "Mid.", 20000, now);

        // No search term: the relevance key is a constant, so priceLow drives the order.
        PagedResponse<ExperienceTeaserResponse> page = browse(null, null, null, null, null, null, "priceLow");

        assertThat(page.items())
                .extracting(ExperienceTeaserResponse::pricePaise)
                .containsExactly(10000L, 20000L, 30000L);
    }
}
