package com.knowyourinterview.api.experience;

import java.sql.Timestamp;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

import com.knowyourinterview.api.experience.dto.ExperienceTeaserResponse;
import com.knowyourinterview.api.support.ContainerConfig;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Testcontainers coverage for the "did you mean" fallback ({@code ExperienceService#suggest} /
 * {@code GET /api/v1/experiences/suggestions}). Like {@link BrowseSearchIT}, it exercises a
 * hand-written NATIVE pg_trgm query ({@code ExperienceRepository#suggestPublished}) against a
 * real Flyway-migrated Postgres — the generated columns, {@code similarity()}, and the computed
 * ORDER BY can't be exercised by a mocked repository. Run with {@code mvn verify} (needs Docker).
 *
 * <p>The point of this endpoint is that it fires when a strict browse matched nothing, so the
 * assertions below deliberately use queries that DON'T exactly match — a typo'd company and an
 * abbreviated role — and still expect the closest published rows back, ranked by relevance.
 */
@SpringBootTest
@Import(ContainerConfig.class)
class SuggestionsIT {

    /**
     * Pin the suggestion threshold to its documented default so the near-miss cases
     * ("Beckend" vs "Backend Engineer") clear the bar regardless of the ambient config. This is
     * the separate, lower cutoff from the 0.3 search threshold — the whole reason suggestions
     * can surface matches a strict search would drop.
     */
    @DynamicPropertySource
    static void suggestionProperties(DynamicPropertyRegistry registry) {
        registry.add("app.search.suggestion-threshold", () -> "0.15");
        // No test may open an SMTP connection; blank host => LoggingEmailSender.
        registry.add("spring.mail.host", () -> "");
    }

    @Autowired
    private ExperienceService experienceService;

    @Autowired
    private JdbcTemplate jdbc;

    private UUID contributorId;

    @BeforeEach
    void seedContributor() {
        jdbc.execute("TRUNCATE experiences, users CASCADE");
        contributorId = UUID.randomUUID();
        jdbc.update(
                "INSERT INTO users (id, email, password_hash, display_name, is_admin, email_verified) "
                        + "VALUES (?, ?, 'x', 'Seed Contributor', false, true)",
                contributorId, "seed-" + contributorId + "@example.test");
    }

    /** Inserts a PUBLISHED experience and returns its id. Normalized columns are generated by
     * Postgres, so they're deliberately not in the column list. */
    private UUID seedPublished(String company, String roleTitle, String level, String teaser,
                               long pricePaise, Instant publishedAt) {
        UUID id = UUID.randomUUID();
        jdbc.update("""
                INSERT INTO experiences
                    (id, contributor_id, company, role_title, level, is_remote, outcome, teaser,
                     price_paise, status, is_free, created_at, updated_at, published_at)
                VALUES (?, ?, ?, ?, ?, false, 'OFFER', ?, ?, 'PUBLISHED', false, now(), now(), ?)
                """,
                id, contributorId, company, roleTitle, level, teaser, pricePaise,
                Timestamp.from(publishedAt));
        return id;
    }

    private List<ExperienceTeaserResponse> suggest(String q, int limit) {
        return experienceService.suggest(null, q, limit);
    }

    @Test
    void typoInRoleStillReturnsClosestMatchViaTrigramSimilarity() {
        Instant now = Instant.now();
        seedPublished("Acme", "Backend Engineer", "L5", "Interview experience.", 9900, now);
        seedPublished("Globex", "Frontend Designer", "L4", "Interview experience.", 9900, now);

        // "Beckend" matches neither the normalized-contains nor the teaser substring, so this
        // only passes via the pg_trgm similarity path — exactly the fallback's reason to exist.
        List<ExperienceTeaserResponse> results = suggest("Beckend", 6);

        assertThat(results)
                .extracting(ExperienceTeaserResponse::roleTitle)
                .contains("Backend Engineer")
                .doesNotContain("Frontend Designer");
    }

    @Test
    void abbreviatedRoleReturnsMatchingRolesRankedByRelevance() {
        Instant now = Instant.now();
        seedPublished("Acme", "SDE-1", "L3", "One.", 9900, now);
        seedPublished("Globex", "SDE-2", "L4", "Two.", 9900, now);
        seedPublished("Umbrella", "Product Manager", "L5", "Unrelated.", 9900, now);

        // "SDE" normalizes to "sde" and matches every SDE-* role; the PM row is excluded.
        List<ExperienceTeaserResponse> results = suggest("SDE", 6);

        assertThat(results)
                .extracting(ExperienceTeaserResponse::roleTitle)
                .containsExactlyInAnyOrder("SDE-1", "SDE-2");
    }

    @Test
    void closerMatchIsRankedFirst() {
        Instant earlier = Instant.now().minus(2, ChronoUnit.HOURS);
        Instant later = Instant.now();
        // Exact company, published EARLIER.
        seedPublished("Stripe", "Engineer", "L5", "Interview experience.", 9900, earlier);
        // Weaker (substring) match, published LATER — recency-first would put this first, so it
        // landing SECOND proves relevance outranks recency in the suggestion ordering too.
        UUID weaker = seedPublished("Stripe Payments Platform", "Engineer", "L5",
                "Interview experience.", 9900, later);

        List<ExperienceTeaserResponse> results = suggest("stripe", 6);

        assertThat(results).hasSize(2);
        assertThat(results.get(0).company()).isEqualTo("Stripe");
        assertThat(results.get(1).id()).isEqualTo(weaker);
    }

    @Test
    void blankQueryReturnsEmptyWithoutQuerying() {
        Instant now = Instant.now();
        seedPublished("Acme", "Backend Engineer", "L5", "Interview experience.", 9900, now);

        assertThat(suggest("   ", 6)).isEmpty();
        assertThat(suggest(null, 6)).isEmpty();
    }

    @Test
    void limitIsRespected() {
        Instant now = Instant.now();
        // Five rows that all match "engineer" on the role.
        for (int i = 0; i < 5; i++) {
            seedPublished("Company" + i, "Engineer", "L5", "Interview experience.", 9900, now);
        }

        assertThat(suggest("engineer", 2)).hasSize(2);
        // Below-range and above-range limits clamp to 1..12 rather than erroring.
        assertThat(suggest("engineer", 0)).hasSize(1);
        assertThat(suggest("engineer", 999)).hasSize(5);
    }
}
