-- Know Your Interview — initial schema (Phase 1)
-- Amounts are stored in paise (INR minor unit). IDs are UUIDs generated by the app.

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(255) NOT NULL,
    is_admin        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE experiences (
    id                  UUID PRIMARY KEY,
    contributor_id      UUID NOT NULL REFERENCES users(id),
    company             VARCHAR(255) NOT NULL,
    role_title          VARCHAR(255) NOT NULL,
    level               VARCHAR(100),
    location            VARCHAR(255),
    is_remote           BOOLEAN NOT NULL DEFAULT FALSE,
    interview_month      SMALLINT,
    interview_year       SMALLINT,
    outcome             VARCHAR(50) NOT NULL,          -- OFFER | REJECTED | WITHDRAWN
    teaser              TEXT NOT NULL,
    prep_advice         TEXT,
    overall_difficulty  SMALLINT,                      -- 1-5
    timeline             VARCHAR(255),
    compensation         VARCHAR(255),                  -- optional, free text
    price_paise          INTEGER NOT NULL,               -- platform-fixed price at time of publish
    status               VARCHAR(50) NOT NULL DEFAULT 'DRAFT', -- DRAFT | PENDING_REVIEW | APPROVED | REJECTED | PUBLISHED
    rejection_reason      TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at          TIMESTAMPTZ
);

CREATE INDEX idx_experiences_contributor ON experiences(contributor_id);
CREATE INDEX idx_experiences_status ON experiences(status);
CREATE INDEX idx_experiences_company_role ON experiences(company, role_title);

CREATE TABLE experience_rounds (
    id                     UUID PRIMARY KEY,
    experience_id          UUID NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
    round_number            SMALLINT NOT NULL,
    round_type              VARCHAR(100) NOT NULL,       -- e.g. PHONE_SCREEN, ONSITE, SYSTEM_DESIGN
    duration_minutes         SMALLINT,
    questions_asked           TEXT,
    topics_tags               VARCHAR(500),               -- comma-separated tags for MVP
    approach                   TEXT,
    interviewer_behavior       TEXT,
    difficulty                 SMALLINT,                    -- 1-5
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_experience_rounds_experience ON experience_rounds(experience_id);

CREATE TABLE proof_documents (
    id              UUID PRIMARY KEY,
    experience_id   UUID NOT NULL REFERENCES experiences(id) ON DELETE CASCADE,
    s3_key          VARCHAR(1024) NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    content_type    VARCHAR(100) NOT NULL,
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_proof_documents_experience ON proof_documents(experience_id);

CREATE TABLE purchases (
    id                    UUID PRIMARY KEY,
    user_id               UUID NOT NULL REFERENCES users(id),
    experience_id         UUID NOT NULL REFERENCES experiences(id),
    amount_paise          INTEGER NOT NULL,
    razorpay_order_id     VARCHAR(255),
    razorpay_payment_id   VARCHAR(255),
    status                VARCHAR(50) NOT NULL DEFAULT 'CREATED', -- CREATED | PAID | FAILED
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_purchases_user ON purchases(user_id);
CREATE INDEX idx_purchases_experience ON purchases(experience_id);

CREATE TABLE entitlements (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id),
    experience_id   UUID NOT NULL REFERENCES experiences(id),
    purchase_id     UUID NOT NULL REFERENCES purchases(id),
    granted_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, experience_id)
);

CREATE TABLE payout_accounts (
    id                          UUID PRIMARY KEY,
    user_id                     UUID NOT NULL UNIQUE REFERENCES users(id),
    account_holder_name         VARCHAR(255) NOT NULL,
    razorpayx_contact_id        VARCHAR(255),
    razorpayx_fund_account_id   VARCHAR(255),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payouts (
    id                     UUID PRIMARY KEY,
    experience_id          UUID NOT NULL UNIQUE REFERENCES experiences(id),
    contributor_id         UUID NOT NULL REFERENCES users(id),
    amount_paise           INTEGER NOT NULL,
    razorpayx_payout_id    VARCHAR(255),
    status                 VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING | PROCESSING | PAID | FAILED
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE review_logs (
    id              UUID PRIMARY KEY,
    experience_id   UUID NOT NULL REFERENCES experiences(id),
    admin_id        UUID NOT NULL REFERENCES users(id),
    action          VARCHAR(50) NOT NULL, -- APPROVED | REJECTED
    reason          TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_logs_experience ON review_logs(experience_id);
